### ISSUE TITLE
More robust and random OTP.

### ISSUE THREAD

**Issue by Aryaman1706** [Manthan933/Manthan#100]
**Is your feature request related to a problem? Please describe.**
We should have a more robust and random process for OTP generation. Math.random() usually gives similar results when run a few times.

**Describe the solution you'd like**
We can use something like [uuid](https://www.npmjs.com/package/uuid), [shortId](https://www.npmjs.com/package/shortid) or [randomatic](https://www.npmjs.com/package/randomatic) or crypto(built into node).

**Additional context**
- I would like to work on this issue. Could you please assign this to me?
- GSSOC'21 participant

**Comment by aavishkarmishra** [comment]
Please continue with this issue 💯

**Comment by Aryaman1706** [comment]
Hello @aavishkarmishra ! I want to discuss one thing.

**Issue**
- Since `code` is a unique identifier for classroom, this means that no two classrooms should have the same code.
- Now randomizing a 6 letter long string of lowercase, uppercase and digits will not make sure that all of the codes generated are unique.
-  Especially once the project expands, there would be thousands, and thousands of classrooms and each one should have its own unique code which might be conflicting on such a large scale.

**Solution**
I thought of the following solutions:- 
- Index the code field to be unique and on saving to DB, if mongoose throws an error due to duplication, we would generate the code again and try to save that.
- We can segregate code depending on some factors like region, year, month, subject, etc. This way chance of conflicting codes for the same year and month would reduce.
- (Best, in my opinion) We can make expiring codes like if no user has joined the classroom for say a month, then we will remove the code from that classroom and we could use the same code for some other classroom and if a teacher from the first classroom wants to regenerate the code, they can do the same with a click of a button and then that newly generated code would be mapped to the classroom.

I would love to discuss it further(here itself or on discord). 
Your feedback would be highly appreciated and helpful.

**Comment by Aryaman1706** [comment]
Above is the pull request but it generates comparatively random code as of now. 
I would start working on the aforementioned issue (the one talking about unique codes) once we have discussed it thoroughly.

**Comment by Aryaman1706** [comment]
Hello @aavishkarmishra ! I read a bit more about Math.random() and randomatic.
This is how randomatic generates random number:- `res += mask.charAt(parseInt(mathRandom() * mask.length, 10));`. 
As depicted this also uses math.random under the hood with some optimizations.

Giving more thought to the above comment, I figured that the probability of code duplication is rare but still I feel that we should make a safeguard so that the app doesn't crash during production and runtime. 

I feel that the 3rd approach of regenerating code would be an overkill here,  in my opinion, the best we can do is either retry if duplicated code is found or make a format for code that would have other details as well like a code with first 2 digits representing year other representing month and another representing date followed by sequence number or random number.

Eg:- 
`cbC1675` here `cb` represents year (c corresponding to 2 and b corresponding to 1 so hence 21 is the year), `C` is the month(A representing January and Z representing December), `16` is the date today and `75` is a sequence or random number.

Kindly give appropriate suggestions and feedback.
Thank You.

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this as well...
GSSOC'21 participant
