### ISSUE TITLE
Restrict the input text

### ISSUE THREAD

**Issue by iamabhi222** [Manthan933/Manthan#109]
As now we are able to enter the class names, subject and subject code of infinite length we must restrict it to a defined value
![image](https://user-images.githubusercontent.com/56785486/111306936-d73c8100-867e-11eb-9308-9019351bc946.png)

**Comment by arkumari2000** [comment]
Hello, I wanted to give it a try as a participant of gssoc'21
Please assign it to me

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by sanjanasingh31** [comment]
Hello, I m a gssoc'21 participant and I would like to work on this issue.

**Comment by iamabhi222** [comment]
> Hello, I wanted to give it a try as a participant of gssoc'21
> Please assign it to me

On FIFO basis I am assigning you this issue, if you need any help reach out any of the mentors

**Comment by arkumari2000** [comment]
> On FIFO basis I am assigning you this issue, if you need any help reach out any of the mentors
Thank you

**Comment by arkumari2000** [comment]
Can @iamabhi222 you please tell the exact limit of length we are supposed to have in these fields?
