### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by nishant23122000** [Manthan933/Manthan#112]
For now, there is no issue to find a class. but in the future, there is more than 1 class and the user has to scroll down to find their desire class. 

So, I think we should add a search box above the class list. and according to input in the **search box**, the classes will be dynamic change.

**Comment by Vidisha-kayal** [comment]
@nishant23122000 Do you want to work on this?

**Comment by nishant23122000** [comment]
@Vidisha-kayal yes

**Comment by lopeselio** [comment]
Is the issue still open ?
@Vidisha-kayal

**Comment by nishant23122000** [comment]
@lopeselio  I pull this code but i think it's under review
