### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by arkumari2000** [Manthan933/Manthan#113]
**Is your feature request related to a problem? Please describe.**
There is no readme in this project. Although CONTRIBUTING.md is present, but I think this is not enough from installing to running the project for the beginners.

**Describe the solution you'd like**
I think we should add readme file which will state how to install and run the client and server side in your machine after cloning the repo.

**Comment by arkumari2000** [comment]
@iamabhi222 please check if this issue is valid, and if it is please assign it to me under gssoc'21 participant and add labels to it.
Thank you

**Comment by Vidisha-kayal** [comment]
@arkumari2000 This issue has already been resolved.
