### ISSUE TITLE
Adding token based authentication 

### ISSUE THREAD

**Issue by chauhanprakhar** [Manthan933/Manthan#119]
Some features like creating tests should only be restricted to the teacher who is logged in and has their account on Manthan.
I would like to use token-based authentication with a JWT token. If anyone has any other idea of Role-based authentication please suggest, otherwise I would like to work on the token-based authentication system under GSSOC.

**Comment by aavishkarmishra** [comment]
@chauhanprakhar Some of the contributors are working on this issue under #83, you can interact with them if you like.
