### ISSUE TITLE
Delete corresponding tests from database, if the classroom is deleted

### ISSUE THREAD

**Issue by aniketbiswas21** [Manthan933/Manthan#121]
**Is your feature request related to a problem? Please describe.**
If one deletes a classroom, the test related to that classroom is not removed from the database. We can remove that test as this would save storage space.

**Describe the solution you'd like**
We can trigger a remove hook that will look for tests with the classroom code and perform cascade deletion. This hook would be triggered as soon as one deletes a classroom.

**Describe alternatives you've considered**
None.

**Additional context**
If the issue is valid, I would like to work on this. Also, we can remove the corresponding questions to a test when a test is deleted.

**Comment by riyasavant** [comment]
Can I work on this issue?

**Comment by aavishkarmishra** [comment]
@riyasavant @aniketbiswas21  Is there any updated related to this issue ?

**Comment by aniketbiswas21** [comment]
@aavishkarmishra I will make a PR tonight.
