### ISSUE TITLE
add a different home page

### ISSUE THREAD

**Issue by mis-coder** [Manthan933/Manthan#122]
I feel there must be home page (of course different from the main component which is already there).

So we make a home page describing about Manthan and what its all about. We keep it static and make it attractive. And when someone logs in he/she can see the main one which I think is kind of dashboard or personal area for each user.

Please allow me to work on this and help make Manthan better by assigning this issue. I would love to contribute to it.

**Comment by aavishkarmishra** [comment]
@mis-coder Please proceed and add screenshots of UI changes in the pull request.

**Comment by mis-coder** [comment]
> @mis-coder Please proceed and add screenshots of UI changes in the pull request.

Sure!

**Comment by mis-coder** [comment]
@aavishkarmishra  Please check discord! I have sent the prototype.
