### ISSUE TITLE
improve side navber Ui design

### ISSUE THREAD

**Issue by balarka135** [Manthan933/Manthan#123]
I want to improve the side navber UI design of this website. I am a GSSoC participant. I would like to work on this . Please assign me.

**Comment by aavishkarmishra** [comment]
@balarka135 Please mention the UI changes/enhancements you want to apply on navbar .

**Comment by balarka135** [comment]
@aavishkarmishra improvement or new features list in the side nav i want to add
1.  add a calendar in  the side nav as like google classroom
2.  changing the font for better UI.
3.  add a notes app

**Comment by Avnish5** [comment]
Kindly assign this task to me under GSSOC 2021.

**Comment by balarka135** [comment]
Thank u sir for assigning me.

**Comment by balarka135** [comment]
sir, due to the college semester exam I was unable to work for the last three days. Now the exam is over, i worked on 20% on this issue, I will complete it within the next 3 days. Sorry for being late on level 2 issues.

**Comment by AADITYA-SINGH497** [comment]
I want to improve the side navbar UI design of this website. I am a GSsoC participant. I would like to work on this. Please assign me.

**Comment by Devenkapoor7303** [comment]
Can I work on this issue?
