### ISSUE TITLE
Create a new class or join class should be link

### ISSUE THREAD

**Issue by arkumari2000** [Manthan933/Manthan#125]
**Is your feature request related to a problem? Please describe.**
On the main page there is written create a new class or join class. But it is a simple text and not a link which will direct it to create or join class.

**Describe the solution you'd like**
That simple text should be link that will open the form of create a new class or join a class.

**Additional context**
![Screenshot 2021-03-20 at 5 49 28 PM](https://user-images.githubusercontent.com/48750169/111869551-18e26a00-89a6-11eb-9607-2217d7ef5ef4.png)
Here this ***Create a new class or join class*** should be a link to the form of create class and join class respectively and not a simple text.

**Comment by aavishkarmishra** [comment]
@arkumari2000 What is the requirement of link, as after login you can create or join class from floating button in bottom right corner ?

**Comment by arkumari2000** [comment]
> @arkumari2000 What is the requirement of link, as after login you can create or join class from floating button in bottom right corner ?

Yes that I know, but I was saying this for user experience. It will make our user experience better. 
If the person is not logged in and click on this it will direct them to login form first and if the user is logged in then it will directly open the form. 
If you think this will be better for the website then why not implement this?

**Comment by RuchiGitHu** [comment]
> > @arkumari2000 What is the requirement of link, as after login you can create or join class from floating button in bottom right corner ?
> 
> Yes that I know, but I was saying this for user experience. It will make our user experience better.
> If the person is not logged in and click on this it will direct them to login form first and if the user is logged in then it will directly open the form.
> If you think this will be better for the website then why not implement this?

I am able to do so using HTML, CSS.
Please assign this issue to me..
