### ISSUE TITLE
Duplicate Options

### ISSUE THREAD

**Issue by Kriti-bit** [Manthan933/Manthan#129]
**Describe the bug**
Options to a question may not always be unique. I would like to fix this bug. This will ensure that the options for a question are always unique and the same option does not get repeated.

**Expected behavior**
An error should be displayed in case the instructor enters same option twice.

**Screenshots**

![image](https://user-images.githubusercontent.com/69788174/112122050-e2932d80-8be5-11eb-915f-3b43465efb9d.png)

**Comment by Kriti-bit** [comment]
Please assign this issue to me.

**Comment by aavishkarmishra** [comment]
@Kriti-bit is there any update related to this issue ?

**Comment by Kriti-bit** [comment]
@aavishkarmishra I have completed the backend for the issues. Can I create a PR of the same?

**Comment by aavishkarmishra** [comment]
Yes, and you can commit new changes on same branch so the pull request will get updated accordingly.
