### ISSUE TITLE
404 page interrupt  in class route and test route

### ISSUE THREAD

**Issue by VenomFate-619** [Manthan933/Manthan#143]
**Describe the bug**
When I am visiting the classroom page, the 404 page is coming for some second and after that class page is showing up.
On the class page if clicked a floating button to create a test again 404 pages is rendered for some time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a class
2. From dashboard visit classroom page i.e /class/:classId
3. 404 page is up (error )
4. Scroll down to the floating button to create a test
5.  404 page is up (error )

**Expected behaviour**
404 page should not be displayed which routing the class page, test page 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WIN10
 - Browser [e.g. chrome, safari] EDGE
 - Version [e.g. 22] 89.0.774.63

**Additional context**
My internet connection is a little bit slow, but I don't think it is creating a problem and if it is then we should work to resolve it

https://user-images.githubusercontent.com/67755128/113243720-25818f00-92d1-11eb-95c0-7518d9c89dc7.mp4

.

**Comment by aavishkarmishra** [comment]
@VenomFate-619 Are you willing to work on this issue ?

**Comment by VenomFate-619** [comment]
Yes I will do , tell me is docker setup is necessary to run project  , I am new to docker

**Comment by aavishkarmishra** [comment]
> Yes I will do , tell me is docker setup is necessary to run project , I am new to docker
No its not necessary.

**Comment by VenomFate-619** [comment]
share the env.example file

**Comment by VenomFate-619** [comment]
@aavishkarmishra can you assign me this
