### ISSUE TITLE
Adding Custom themes

### ISSUE THREAD

**Issue by nishant23122000** [Manthan933/Manthan#149]
**Is your feature request related to a problem? Please describe.**
I think we should apply themes to our website,

**Describe the solution you'd like**
Till now, we have only white background on each page, but what if we provide an option for custom themes, check below video for a better understanding

https://user-images.githubusercontent.com/53515714/113472979-3faf9e80-9484-11eb-952f-e84f6a7e6d0e.mp4

So we can do this like chrome, where we put a theme option in the drawer section and there are multiple images available and also solid colors, so that user can set his favorite background theme and we will display this theme in each page

**Describe alternatives you've considered**

**Additional context**

**Comment by aavishkarmishra** [comment]
@nishant23122000 would you like to work on this issue?

**Comment by nishant23122000** [comment]
> @nishant23122000 would you like to work on this issue?

Yes sure
