### ISSUE TITLE
Join and Leave Classroom Routes are not working

### ISSUE THREAD

**Issue by Rishi-121** [Manthan933/Manthan#15]
![Screenshot (106)](https://user-images.githubusercontent.com/62418363/103778330-1b484f80-5058-11eb-9cbb-7e7f0568331b.png)
**Describe the bug**
Join and Leave the classroom controllers are not properly configured!

**Comment by Rishi-121** [comment]
I want to resolve this!

**Comment by vikhyatsingh123** [comment]
@Rishi-121 Go ahead

**Comment by Rishi-121** [comment]
Please check my pull request!
