### ISSUE TITLE
[SERIOUS] MongoDB URI committed to repo

### ISSUE THREAD

**Issue by atulya2109** [Manthan933/Manthan#152]
**Describe the bug**
default.json under the config folder has Mongo Uri in the file which is a sensitive information. Sensitive information such as API Tokens and in this case Mongo Uri with the username and password of the data base should not be committed to a public repository. Instead of loading sensitive data this way, one should use a .env file and provide a sample .env for contributors.

**To Reproduce**
1. Goto config/default.json
2. Copy the Mongo URI
3. Paste it in MongoDB Compass
4. See for yourself

**Expected behavior**
Instead of loading sensitive data this way, one should use a .env file and provide a sample .env for contributors.

**Screenshots**
![image](https://user-images.githubusercontent.com/20705464/113484841-0ac53b00-94c8-11eb-81a7-0dc4f025c8ba.png)
Here is the database with all the users that have created their account

**Additional context**
I will implement loading credentials from the .env file meanwhile whomever this MongoDB Atlas account belongs to should change their password

**Comment by atulya2109** [comment]
There are bots on Github that scan for sensitive information that has been committed to public repos so as to use it for their own purposes.

**Comment by atulya2109** [comment]
SInce, loading of environment variables has already been implemented using config I won't be implementing it with dotenv rather I will add the config.json to .gitignore and add a sample config.json file.

**Comment by aavishkarmishra** [comment]
This is added because, so many contributors are having issues with mongo-uri for development. So I added a uri for development purposes.

**Comment by atulya2109** [comment]
You can share it on discord I guess. If you share it this way it might get crawled by bots. Or there could be documentation on how they can locally set up a mongodb server
