### ISSUE TITLE
No students enrolled should be white .

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#160]
No students enrolled should be white .
![Screenshot from 2021-04-10 02-20-28](https://user-images.githubusercontent.com/58372823/114239211-66e5fe80-99a3-11eb-83bb-1c1a764ceb5f.png)

**Comment by M2kishore** [comment]
I think making it red would look more like a warning:)

**Comment by dchhavi** [comment]
I really want to work on this issue.

**Comment by dchhavi** [comment]
@aavishkarmishra Can you please provide me the code directory of this issue?

**Comment by aavishkarmishra** [comment]
> @aavishkarmishra Can you please provide me the code directory of this issue?

@dchhavi You can find it [here](https://github.com/Manthan933/Manthan/blob/main/client/src/components/classroom/Classroom.js#L2080).

**Comment by adysis14** [comment]
Hey! I'm interested in solving this issue . I would be very grateful if you assign this issue to me under GSSOC'21

Thank You!
