### ISSUE TITLE
change theme button and add classroom button overlap!

### ISSUE THREAD

**Issue by M2kishore** [Manthan933/Manthan#161]
**The Bug**
resizing the window cause the add classroom and theme button to overlap
**To Reproduce**
1. resize the browser window to reduce the width

**Expected behavior**
Overlapping of the buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/60045529/114264000-076d0a80-9a06-11eb-88d9-f047cdd7185b.png)
![image](https://user-images.githubusercontent.com/60045529/114264054-50bd5a00-9a06-11eb-8059-6eaf17eb6d9e.png)

**Desktop (please complete the following information):**
 - OS: Linux(Mint)
 - Browser chromium , firefox

**Comment by aavishkarmishra** [comment]
@M2kishore Would you like to work on this issue?

**Comment by M2kishore** [comment]
With some guidance I can work on this

**Comment by M2kishore** [comment]
I can do this but I need some guidance from your side. I have experience with javascript but not with react.
I tried to add a CSS property in ClassButton.js but didn't workout
>`overflow: 'hidden'`
