### ISSUE TITLE
Sign in by Google and Facebook.

### ISSUE THREAD

**Issue by subham-paul** [Manthan933/Manthan#165]
**Describe the feature you'd like**
Adding Sign in with Google and Facebook options.

**Comment by aavishkarmishra** [comment]
@subham-paul Would you like to work on this issue ?

**Comment by naqeeb2710** [comment]
i would like to work on this issue

can u assign me this

**Comment by iamabhi222** [comment]
ok @naqeeb2710  you can work on this

**Comment by Jassi10000** [comment]
Is there any activity on this 
As I also want to try hands on this

**Comment by iamabhi222** [comment]
> Is there any activity on this
> As I also want to try hands on this

yes you can!
