### ISSUE TITLE
 Configure eslint and prettier for the UI application

### ISSUE THREAD

**Issue by PuneetPunamiya** [Manthan933/Manthan#171]
Configure eslint and prettier for the UI application

    The UI application should have a lint and prettier configuration which will
    keep the code in one format (for e.g. proper spacing, etc) and will make
    the code look preetier as well

    Configuring eslint and preetier and executing the commands like
    npm run lint and npx prettier --write . will give the warnings/errors
    which the developers can fix before the code is submitted

**Comment by aavishkarmishra** [comment]
@PuneetPunamiya Would you like to work on this issue?

**Comment by PuneetPunamiya** [comment]
@aavishkarmishra  Yes will you please assign it to me

**Comment by PuneetPunamiya** [comment]
@aavishkarmishra   would you mind if I also submit a patch which fixes the lint errors because after this pr get's merged it would break the application

**Comment by aavishkarmishra** [comment]
> @aavishkarmishra would you mind if I also submit a patch which fixes the lint errors because after this pr get's merged it would break the application
You can include both changes in a single pull request, and I will increase the level the of issue.
