### ISSUE TITLE
Automatic logout after closing the tab

### ISSUE THREAD

**Issue by codebuzzer01** [Manthan933/Manthan#177]
**Describe the bug**
If the user signed in and closes the manthan tab before signing out, a bug occurs which could be seen if user once again visits the website. There is no option of sign-in instead it says log-out.

**To Reproduce**
1. Go to 'www.manthan-app.org!'
2. Click on 'Login and after getting logged in close the tab without logging out '
3. Again open 'www.manthan-app.org'

**Expected behavior**
The expected behaviour is as soon as the user closes the tab, he/she should automatically get logged out and manthan should open with login option again.

**Screenshots**
![Screenshot (221)](https://user-images.githubusercontent.com/52864294/115951719-ea553300-a4ff-11eb-9fa5-292fc0456860.png)
![Screenshot (222)](https://user-images.githubusercontent.com/52864294/115951721-ee815080-a4ff-11eb-8453-d0c249a95c5c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by codebuzzer01** [comment]
@aavishkarmishra Verify this?

**Comment by aavishkarmishra** [comment]
> @aavishkarmishra Verify this?

This is not a bug, you can go to dashboard form navbar. And user is logged in until he logout, so that user do not have login every time.

**Comment by codebuzzer01** [comment]
ok cool.. thnx @aavishkarmishra
