### ISSUE TITLE
Add subject Code in class template

### ISSUE THREAD

**Issue by ShrutiOmer** [Manthan933/Manthan#181]
**Describe the bug**
In the template of classes the Class name overlaps with the options.

**To Reproduce**
1. Go to '..Create Class.'
2. Give  'large name to class name....'
3. Click On 'Class name'
4. A template opens
5. In that menu and class name overlaps

**Expected behavior**
They should not overlaps.

**Screenshots**
![image](https://user-images.githubusercontent.com/75009990/115986820-b8ab9d00-a5cf-11eb-9670-d9ab2fd980a4.png)

**Desktop (please complete the following information):**
 - OS: [microsoft windows]
 - Browser [ chrome]

**Smartphone (please complete the following information):**

**Additional context**
Please assign this issue to me.

**Comment by aavishkarmishra** [comment]
![Screenshot from 2021-04-25 15-45-12](https://user-images.githubusercontent.com/58372823/115989735-6cfff000-a5dd-11eb-909d-0fd9eccd90c4.png)

@ShrutiOmer I am unable observe this bug, might be some issue of browser .

**Comment by ShrutiOmer** [comment]
Yes may be due to browser.

**Comment by ShrutiOmer** [comment]
The subject Code is not mentioned in this template. Can I add this ?

**Comment by aavishkarmishra** [comment]
Yes, @ShrutiOmer  you can if you want to.
