### ISSUE TITLE
Change UI of copy Invite link

### ISSUE THREAD

**Issue by ShrutiOmer** [Manthan933/Manthan#187]
**Is your feature request related to a problem? Please describe.**
Copy Invite link button is not different from other content. I want to change UI for this button.

**Describe the solution you'd like**
   I can  make button look like
![invite link](https://user-images.githubusercontent.com/75009990/116091220-410a6a80-a6c2-11eb-97b5-2d8dbb20fc93.png)
  Currently it is looking like
      
![invite link](https://user-images.githubusercontent.com/75009990/116091669-af4f2d00-a6c2-11eb-90c7-b1a3e8d539f9.png)

Please assign issue to me.

**Comment by iamabhi222** [comment]
you can use a <Tooltip/> rather than button it may look good!

**Comment by ShrutiOmer** [comment]
@iamabhi222 can you elaborate more, I am not able to understand

**Comment by iamabhi222** [comment]
check material-ui tooltip component

**Comment by ShrutiOmer** [comment]
Okk I will try to use that.

**Comment by ShrutiOmer** [comment]
![image](https://user-images.githubusercontent.com/75009990/116875808-2479af80-ac39-11eb-9eb9-eae1d4f1829a.png)
See I have made it like this. If its fine I will make pr @iamabhi222
