### ISSUE TITLE
Enable Lint Check In Github Actions

### ISSUE THREAD

**Issue by PuneetPunamiya** [Manthan933/Manthan#191]
Since we have eslint and preetier configured now, should we add lint checks in Github Actions so that lint will be checked when a pr is raised and reviewer will not have to do it manually since Github Actions will already do it

**Comment by PuneetPunamiya** [comment]
@aavishkarmishra  Could you please assign me this issue ?

**Comment by adysis14** [comment]
Hey! I'm interested in solving this issue . I would be very grateful if you assign this issue to me under GSSOC'21

Thank You!
