### ISSUE TITLE
UPDATE & DELETE endpoints for USERS

### ISSUE THREAD

**Issue by Vishal1003** [Manthan933/Manthan#204]
**Feature Request**
Once a user is entered there is no option to update his profile (his name, email etc.). Suppose I entered a wrong name while registering then there should be an option there to update that. Moreover it is very much possible that the admin wants to delete an unauthorized profile then there should be an option to delete the user as well.

**Solution**
I'll be adding the update and delete endpoint in the backend which can be further integrated with the UI (I guess there already exists an issue which is based on the settings page)

@iamabhi222  Kindly check this issue and assign me if it makes sense?! Thank you

**Comment by iamabhi222** [comment]
we were expecting this issue to be solved in #168 but now I think if you want to work on this than you also need to create the setting page
