### ISSUE TITLE
Homepage is not responsive

### ISSUE THREAD

**Issue by garvitgupta13** [Manthan933/Manthan#209]
**Describe the bug**
The `All rights reserved. Copyright © Manthan 2021` overlays the heading of welcome page

**To Reproduce**
1. Go to chrome inspect
2. Switch to mobile
3. See error

**Expected behavior**
The copyright statement should be at the end of page

**Screenshots**
![image](https://user-images.githubusercontent.com/70805691/118017557-63fc7600-b374-11eb-9f1a-371fb487aade.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by garvitgupta13** [comment]
Please assign me this issue under `gssoc21`

**Comment by shiv-30** [comment]
I am a gssoc'21 participant and I want to work on this issue.
So please assign this issue to me.

**Comment by garvitgupta13** [comment]
Hey @iamabhi222 I have observed that in the localhost the footer is already fixed but the heading is distorted, so can I fix that under this issue and create a PR
![image](https://user-images.githubusercontent.com/70805691/118238304-f9ebea00-b4b5-11eb-82d8-c15d6c0ac593.png)

**Comment by garvitgupta13** [comment]
I have fixed the heading, can I create a PR
![image](https://user-images.githubusercontent.com/70805691/118239148-06bd0d80-b4b7-11eb-8e33-8e23ee55623b.png)

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by iamabhi222** [comment]
> I have fixed the heading, can I create a PR
> ![image](https://user-images.githubusercontent.com/70805691/118239148-06bd0d80-b4b7-11eb-8e33-8e23ee55623b.png)

yes
