### ISSUE TITLE
Bug : "Teacher can create test without providing test name and marks"

### ISSUE THREAD

**Issue by RitikPandey1** [Manthan933/Manthan#21]
**Describe the bug**
Teacher can create test without providing test name and marks  

**To Reproduce**
1. Go to 'class'
2. Click on '+' icon in bottom to create test
3. Then click next without adding  name and marks 

**Expected behavior**
It will show an error and also not move further  if teacher doesn't  provide test name and marks.

**Comment by RitikPandey1** [comment]
I would like to resolve this bug

**Comment by aavishkarmishra** [comment]
Assigning this issue to you 👍🏻
