### ISSUE TITLE
"Copy invite link" button doesn't work?

### ISSUE THREAD

**Issue by AmrutaKoshe** [Manthan933/Manthan#215]
**Describe the bug**
After creating a class, a copy invite link button is displayed on the screen to share the link with others. However, after pasting, there is nothing that is copied. Is that just a dummy button? 

**To Reproduce**
1. Go to http://www.manthan-app.org/
2. Click on Login and enter your details
3. Create a new class with all the details
4. Click on the copy invite link button and try pasting it.

**Expected behavior**
After pasting, an invite link should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/59871941/118660910-431ca080-b80c-11eb-98fd-9b0bff433022.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by VenomFate-619** [comment]
Can i work on this issue

**Comment by aavishkarmishra** [comment]
This feature works correctly in the local host so I have no idea why this is happening.
@AmrutaKoshe @VenomFate-619
If anyone of you have a solution for it you can work on this issue. I would also like to know why this is happening 😃

**Comment by Siddhant-K-code** [comment]
If anybody wants to work on this, just fix this line: https://github.com/Manthan933/Manthan/blob/main/client/src/components/classroom/Classroom.js#L116

**Comment by AmrutaKoshe** [comment]
> If anybody wants to work on this, just fix this line: https://github.com/Manthan933/Manthan/blob/main/client/src/components/classroom/Classroom.js#L116

Okay will try it. Thankyou!

**Comment by AmrutaKoshe** [comment]
@aavishkarmishra Hey! I have created a pr... and it works on local host , but there's no way for me to tell whether it will also work on the main site ... so can you check it
