### ISSUE TITLE
Footer covers the heading

### ISSUE THREAD

**Issue by garvitgupta13** [Manthan933/Manthan#216]
**Describe the bug**
Multiple footers are present

**To Reproduce**

**Expected behavior**
Only 1 footer should be there and the other one needs to be removed

**Screenshots**
![image](https://user-images.githubusercontent.com/70805691/118806541-d6b1a800-b8c4-11eb-9723-30ff79ffc500.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
`NA`

**Comment by adysis14** [comment]
Hey! I'm interested in solving this issue . I would be very grateful if you assign this iisue to me under GSSOC'21

Thank You!

**Comment by garvitgupta13** [comment]
I will be creating PR by today
