### ISSUE TITLE
Integration of welcome bot

### ISSUE THREAD

**Issue by Sloth-Panda** [Manthan933/Manthan#25]
Welcome bot can be integrated which will help first timers when they make their first pr or raise their first issue and so

**Comment by imakash3011** [comment]
I would like to work on this issue.

**Comment by imakash3011** [comment]
I would like to work on this issue.

**Comment by aavishkarmishra** [comment]
I am assigning this issue to you.

**Comment by Sloth-Panda** [comment]
hey @aavishkarmishra can you please assign it to me too

**Comment by aavishkarmishra** [comment]
> hey @aavishkarmishra can you please assign it to me too
The pull request for this issue has been created,  @Sloth-Panda  you can look out for more issues.
