### ISSUE TITLE
Page to give test 

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#27]
### Create a page to give test and after submission add the scores to the scores array.

- Have to create frontend page for test
- Have to create an api that will add score of student to scores array
- Have to integrate this api to frontend.

**Comment by Kathuria** [comment]
@aavishkarmishra :Can I work on one of the task like frontend page for test and can integrate api if anyone else can help to create.

Please provide designs if any or idea for the same.

**Comment by Kathuria** [comment]
@aavishkarmishra : I will start working on it, In meantime Can you please assign me this issue.

**Comment by piyushsharma21** [comment]
Hello, @aavishkarmishra : I can contribute on second task `_Have to create an API that will add score of student to scores array_`
Let me know if you have any structure in mind.

**Comment by aavishkarmishra** [comment]
> @aavishkarmishra :Can I work on one of the task like frontend page for test and can integrate api if anyone else can help to create.
> 
> Please provide designs if any or idea for the same.

I have created an API for that you can check it in test routes, it provides question and their correct answers.
