### ISSUE TITLE
Option for students to leave classrooms 

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#28]
There is no option to leave classroom.
So please create an option to leave classroom for students only.

**Comment by pccoder-2000** [comment]
I would like to work on this issue :)

**Comment by aavishkarmishra** [comment]
I am assigning this issue to you.
Happy contributing 💯

**Comment by Kathuria** [comment]
@pccoder-2000 , @aavishkarmishra : While working on adding an option to delete class - I added an icon of deletion into card.
This can act as triggering place for this case where you can apply API for leaving class or similar to that.
![Delete and Edit](https://user-images.githubusercontent.com/19428377/107870899-bc7dbd80-6ec2-11eb-9c5b-9a4640108a90.PNG)

**Comment by aavishkarmishra** [comment]
> @pccoder-2000 : Are you working on this,
> @aavishkarmishra : I can work on this as well if this issue is available to pick. I can also help someone to complete this task.

Yes please proceed with issue.

**Comment by Kathuria** [comment]
@aavishkarmishra : This is also done, Please review and approve.
