### ISSUE TITLE
Should be a Numeric Value in Duration Box

### ISSUE THREAD

**Issue by ShubhamChaudharyy** [Manthan933/Manthan#29]
When you create description of a test, the duration column should have a formatted input in form of hours and minutes rather than this format i.e at present -> "17:18" this should be like "x hours 2 minutes".
Ideas->
You can use moment.js for time functionality
![Screenshot (317)](https://user-images.githubusercontent.com/43263087/106355719-d5616d00-631f-11eb-995f-7234421cc1a2.png)

**Comment by Kathuria** [comment]
@aavishkarmishra : Can I work on this issue, Instead of using moment.js I would try to find lighter alternative for this conversion.

**Comment by Kathuria** [comment]
@aavishkarmishra : I will start working on it, In meantime Can you please assign me this issue.

**Comment by Kathuria** [comment]
@ShubhamChaudharyy , @aavishkarmishra : Added a fix, Please review.
