### ISSUE TITLE
API key for security

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#3]
Secure the APIs by using api _key or other methods.

**Comment by aavishkarmishra** [comment]
Please, take care of this issue @kartikpapney

**Comment by aavishkarmishra** [comment]
@vidisha-kayal

**Comment by Rishi-121** [comment]
Hey @aavishkarmishra, here we can add the RBAC mechanism for more route protection!

**Comment by aavishkarmishra** [comment]
Hello, @Rishi-121 are you still working on this issue ? 
Please create a pull request if you need any help, or if you are not interested then we can assign this issues to someone else.

This issue will be reassigned to you, whenever you create a pull request regarding this issue.
