### ISSUE TITLE
Making class code only visible for instructor.

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#4]
**Please make the class code only visible to teacher/instructor**
In a class card in class code is accessible by everyone who join the class, please make it visible for only class instructor 
![Screenshot from 2020-12-28 19-59-08](https://user-images.githubusercontent.com/58372823/103221078-c9ad1000-4947-11eb-8422-aae0e88b2f5d.png)

**Comment by Rishi-121** [comment]
In the server, I can add an extra key as a role for the instructor and students, then on the front-end, We can easily validate that one, and as per that, we can render.

**Comment by aavishkarmishra** [comment]
Hello, @Rishi-121 are you still working on this issue ? 
Please create a pull request if you need any help, or if you are not interested then we can assign this issues to someone else.

This issue will be reassigned to you, whenever you create a pull request regarding this issue.

**Comment by deepthiteki** [comment]
Hey, Can I work on this?

**Comment by aavishkarmishra** [comment]
Yes, I am assigning this you @deepthiteki.
