### ISSUE TITLE
Grammatical errors in README.md file

### ISSUE THREAD

**Issue by anirudhsai20** [Manthan933/Manthan#45]
There are a lot of grammatical errors in the README.md file and few the sentecnces can be rephrased to better describe the project.

**Comment by anirudhsai20** [comment]
Hi @manthan933. Please allow me to work on this issue under GSSOC.

**Comment by aavishkarmishra** [comment]
@anirudhsai20 You can proceed with this issue but **remember to create your pull requests after 8 March** as contributions period of GSSOC21 will start from 8 March.

**Comment by SumaiyaSafdar** [comment]
hello, I'll be glad to contribute to this issue .

**Comment by SumaiyaSafdar** [comment]
please assign it to me under GSSCO'21
