### ISSUE TITLE
Documentaion for docker installation

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#46]
There is an option to run app in development environment using **docker**, but there is not proper documentation for this.
Please add the respective documentation in README and wiki.

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue under GSSOC 21, i would like to work on this issue

**Comment by sukhpreet-singh1** [comment]
@aavishkarmishra can you please tell ,i have to write documentation for installing docker or for running application through docker

**Comment by aavishkarmishra** [comment]
Running the application through docker.

**Comment by aavishkarmishra** [comment]
> @aavishkarmishra can you please tell ,i have to write documentation for installing docker or for running application through docker

You have to write the documentation for running the application using docker.

**Comment by rahulii** [comment]
Hi @sukhpreet-singh1 , Please let me know if you are working on this issue, otherwise i ll take on.

**Comment by sukhpreet-singh1** [comment]
i am working on this and had made pull request also regarding the same

**Comment by rahulii** [comment]
Hi @aavishkarmishra ,let me take over the issue!
