### ISSUE TITLE
Add more login options

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#47]
There is only option for login using Google. It will be better if we can login using other platforms too ( as facebook, github etc. )

Add more login options as github and others.

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue under GSSOC 21, i would like to work on this issue

**Comment by Itsaadarsh** [comment]
Hey there @aavishkarmishra, I'd like to work on this feature. So if it's not already assigned to anyone I'd like you it assign it to me so that I could get started right away.

**Comment by aavishkarmishra** [comment]
@sukhpreet-singh1 as you are assigned to an issue, let @Itsaadarsh take this one.  And @Itsaadarsh ping me if anything is required from my side. 

Happy contributing 👍🏻

**Comment by codebuzzer01** [comment]
Hey I would like to work on this issue.
@aavishkarmishra

**Comment by Itsaadarsh** [comment]
Hello there @aavishkarmishra, I've written all the logic required for logging in with Facebook but I'll be needing an `appID` to connect with facebook's API, so while building this feature I created an demo `appID` by visiting here [developers.facebook.com](https://developers.facebook.com/)

So can you visit [developers.facebook.com](https://developers.facebook.com/) and create an account there and register this platform and provide me with the `appID`.

For more reference check out this [video](https://www.youtube.com/watch?v=ZqDeyzXNOoE])

**Comment by hrushikesh-git** [comment]
Hello @aavishkarmishra I would like to work on this issue under GSSOC'21 can you assign it to me?

**Comment by aavishkarmishra** [comment]
> Hello there @aavishkarmishra, I've written all the logic required for logging in with Facebook but I'll be needing an `appID` to connect with facebook's API, so while building this feature I created an demo `appID` by visiting here [developers.facebook.com](https://developers.facebook.com/)
> 
> So can you visit [developers.facebook.com](https://developers.facebook.com/) and create an account there and register this platform and provide me with the `appID`.
> 
> For more reference check out this [video](https://www.youtube.com/watch?v=ZqDeyzXNOoE%5D)

@Itsaadarsh  Create a pull request with a placeholder for **App  Id** I will add that there.
