### ISSUE TITLE
Add delete test option

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#48]
There is no option to delete test in current updated.
Please add **delete test** option to delete specific test.

**Comment by Sukriti-sood** [comment]
@aavishkarmishra  Can you assign this to me

**Comment by samridhikots** [comment]
@aavishkarmishra Can you assign this to me?

**Comment by aavishkarmishra** [comment]
@Sukriti-sood @samridhikots Don't wait for someone to assign you, you can create a pull request whenever you want.
Please make your pull request, we will be assigning issues after pull requests has been created.

**Comment by Ruchip16** [comment]
@aavishkarmishra ok

**Comment by Ruchip16** [comment]
@aavishkarmishra  I have created a PR for this issue, do checkout

**Comment by Sukriti-sood** [comment]
@aavishkarmishra  I have made changes and sent a PR.Please Check it.
