### ISSUE TITLE
Unable multiple submission for a test. 

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#49]
**Describe the bug**
In current updated user can send multiple submission for same test which should not be allowed.  

**To Reproduce**
-  Start any test and submit it.
-  Check whether you are able to submit again for same test .
-  See error.....

**Expected behavior**
User should not be able to open a test more than once.

**Comment by subhangi2731** [comment]
can you please assign this to me?

**Comment by anshika208** [comment]
Hey ! I will like to work on this issue.. can you assign it to me please.

**Comment by srisatya1197** [comment]
I want to contribute to Unable multiple submission for a test issue. Please assign me this task as a part of GSSoC'21

**Comment by aavishkarmishra** [comment]
@subhangi2731 @anshika208 @srisatya1197  
Please create your pull request, first valid pull request will be considered. 
If required any help regarding issue or any other doubts just ping me.

Happy contributing 💯

**Comment by Jaagrav** [comment]
Yeahh I would like to work on this issue as well, assign me pls

**Comment by aavishkarmishra** [comment]
@subhangi2731 @anshika208 Are any one of you is working on this issue ? 
Please create a pull request as soon as possible.

**Comment by anshika208** [comment]
yes i m working on it  and soon will create a pr.

**Comment by Avnish5** [comment]
Kindly assign this task to me under GSSOC 2021.
