### ISSUE TITLE
Unable to create class

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#5]
**Describe the bug**
Unable to create classroom when submitting it only with `class name`

**To Reproduce**
1. Go to Create Class
2. Submit the form with class name only.
3. You can see that classroom is not created.

**Expected behavior**
It should create class without `subject` and `subject code`

**Screenshots**
![Screenshot from 2020-12-29 15-39-10](https://user-images.githubusercontent.com/58372823/103281862-0c2f2500-49fa-11eb-9608-d27c03515286.png)

**Additional context**

**Comment by RitikPandey1** [comment]
I'd like to work on thi issue

**Comment by aavishkarmishra** [comment]
> I'd like to work on this issue

**Comment by aavishkarmishra** [comment]
Yes, @RitikPandey1 please continue with this issue.

**Comment by RitikPandey1** [comment]
Ok 👍

**Comment by RitikPandey1** [comment]
while running the application in my local system,  I was not able to login and got this error. 
@aavishkarmishra,  please check this out 

![error2](https://user-images.githubusercontent.com/57366926/103455895-0f3a5600-4d17-11eb-9628-dda78267fc7a.PNG)

**Comment by aavishkarmishra** [comment]
> while running the application in my local system, I was not able to login and got this error.
> @aavishkarmishra, please check this out
> 
> ![error2](https://user-images.githubusercontent.com/57366926/103455895-0f3a5600-4d17-11eb-9628-dda78267fc7a.PNG)

Please `git pull` and then restart the **client app**.  If problem continues then check your internet connection _**for login and other operations internet should be connect**_.

**Comment by RitikPandey1** [comment]
It still showing "falied to log in".
In devtools it shows some issue regarding cookies.
 
![err](https://user-images.githubusercontent.com/57366926/103457326-45ca9d80-4d24-11eb-9bde-efabbc90f939.PNG)

**Comment by aavishkarmishra** [comment]
@mohit355 Please look into this problem. Is this happening in your system also ?

> while running the application in my local system, I was not able to login and got this error.
> @aavishkarmishra, please check this out
> 
> ![error2](https://user-images.githubusercontent.com/57366926/103455895-0f3a5600-4d17-11eb-9628-dda78267fc7a.PNG)

**Comment by RitikPandey1** [comment]
I am facing same issue  on this link also :- https://manthan-app.herokuapp.com/

![error2](https://user-images.githubusercontent.com/57366926/103457789-4bc27d80-4d28-11eb-9908-37dd3654dcb5.PNG)

**Comment by RitikPandey1** [comment]
Now it works,  third party cookies are blocked in my browser due to which this happened
