### ISSUE TITLE
Countdown timer durnig test

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#50]
There is no option to check how much time is left.
According to me countdown timer could can solve this problem.

**Any other ideas will be appreciated** 👍🏻 💯

**Comment by Ruchip16** [comment]
@aavishkarmishra Can I work on this issue?

**Comment by Ruchip16** [comment]
@aavishkarmishra  I have created  a pull request for this bug Do check it out 
 https://github.com/Ruchip16/Manthan/pull/new/ruchicdtimer
https://github.com/aavishkarmishra/Manthan/pull/2

**Comment by krishna-y2000** [comment]
@aavishkarmishra  Can I work on this issue to solve your problem . I am participant of GSSOC'21.

**Comment by srisatya1197** [comment]
ok cool!

**Comment by Vidisha-kayal** [comment]
@srisatya1197 Do you want to work on this issue?

**Comment by Ruchip16** [comment]
@Vidisha-kayal  mam, I am already working on this issue actually due to a few interviews lined-up I have put this on hold for, but I am already up with code, but I am constantly getting mongoose error that's y it's stuck up

**Comment by Vidisha-kayal** [comment]
@Ruchip16 ok continue with it

**Comment by Ruchip16** [comment]
@aavishkarmishra I am sorry for making PR I am working on it will give you a PR request today please assign me this issue

**Comment by Ruchip16** [comment]
@aavishkarmishra I have to add a countdown timer function in src/components/TestCard/TestCard.js right?

**Comment by aavishkarmishra** [comment]
It will be in the `client/components/tests/Test.js`. It will show how much time left for the test.

**Comment by kunal299** [comment]
@aavishkarmishra Hey, I am interested in solving this issue. Plz assign it to me.

**Comment by kunal299** [comment]
@aavishkarmishra Hey I am facing this error. Plz help me out with this.
![image](https://user-images.githubusercontent.com/71486434/113900602-9fdb7300-97eb-11eb-9f85-6d836e772637.png)

**Comment by kunal299** [comment]
@aavishkarmishra Sir, please help me out

**Comment by aavishkarmishra** [comment]
> @aavishkarmishra Sir, please help me out

use git pull and try reinstalling node modules and keep your internet connection on.
I don't know exactly why this error is coming.
