### ISSUE TITLE
Not properly aligned number of enrolled

### ISSUE THREAD

**Issue by surajondev** [Manthan933/Manthan#51]
**Describe the bug**
In the navigation bar, under the enrolled the number of enrolled is not aligned properly.

**To Reproduce**
1. Go to `http://www.manthan-app.org/`
2. Click on 'Navigation three line'
3. Under the `enrolled`

**Expected behavior**
It should be aligned just below the enrolled button and also in bold to show the importance of the enrolled number.

**Screenshots**
![Capsture](https://user-images.githubusercontent.com/67496096/110322604-66231b00-8039-11eb-8378-cc494d20a920.PNG)

**Desktop (please complete the following information):**
 

**Additional context**
If you would like then I will fix the issue.

**Comment by Nidhikamewar15** [comment]
I would like to work on this issue under GSSOC

**Comment by GuptaTanisha** [comment]
Can I work on this?

**Comment by Abhishek765** [comment]
I would like to work on this ??

**Comment by digbijaya20** [comment]
Can I work on this?

**Comment by srisatya1197** [comment]
I want to contribute to Not properly aligned number of enrolled. Please assign me this task as a part of GSSoC'21

**Comment by Abhishek765** [comment]
@aavishkarmishra , @surajondev  please check I have created a new PR  #79
