### ISSUE TITLE
Imporve performance & automatically fetch questions from csv or excel or json file 

### ISSUE THREAD

**Issue by AakankshaShah** [Manthan933/Manthan#57]
As we are using material-ui for frontend ,the website is quite slow.I can work on it and improve it.
Also I would like to add a feature to automatically fetch questions from csv or excel or json file.

Please assign me this under GSSOC'21 participant.

**Comment by aavishkarmishra** [comment]
@AakankshaShah I am assigning this issue to you, as this issue is quite big so I would like know your strategy and how much time it will take.

**Comment by Esha-Sherring** [comment]
I would also like to contribute. I can also in coordination as this is a big issue

**Comment by AakankshaShah** [comment]
@aavishkarmishra  I will try to complete it within 2 weeks .I will use backend server for extracting the questions from the file because handling with csv and json  is easy with NodeJs.
