### ISSUE TITLE
pr template

### ISSUE THREAD

**Issue by Sloth-Panda** [Manthan933/Manthan#58]
**Is your feature request related to a problem? Please describe.**

There is no pull request template so would like to add one

**Describe the solution you'd like**

It will help understanding pr better

**Comment by Ruchip16** [comment]
@Sloth-Panda  Can you describe deeply whats the issue, I didn't understand, as I am interested to work on this issue so can you elaborate further?

**Comment by Ruchip16** [comment]
@Sloth-Panda Can I work on this issue?

**Comment by Ruchip16** [comment]
@Sloth-Panda Okay cool, thanks
