### ISSUE TITLE
Edit and delete option for classroom

### ISSUE THREAD

**Issue by Vidisha-kayal** [Manthan933/Manthan#6]
**Problem**
There is no option to leave or edit the classroom
It requires an **edit option so that the teacher** who creates the particular classroom can modify it and a **delete option so that the classroom can be deleted** after completion of the test.
**Screenshots**
![Screenshot from 2020-12-28 19-59-08](https://user-images.githubusercontent.com/58372823/103282284-48af5080-49fb-11eb-9a80-ccb5fae3376e.png)

**Comment by Kathuria** [comment]
@aavishkarmishra : Can I work on this?
Requirement:
Edit - Can allow editing of all values? like subject, subject code and class code, anything unique should be there always to identify classroom (id must be same - not checked code yet).

Delete: Particular id should be deleted for classroom after test.

**Comment by Kathuria** [comment]
@aavishkarmishra : I will start working on it, In meantime Can you please assign me this issue.

**Comment by Kathuria** [comment]
@aavishkarmishra , @Vidisha-kayal : Both Required flow are done, Please review the changes
