### ISSUE TITLE
Automatic Test submission

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#61]
**Describe the bug**
Test should automatically be submitted after time runs out. 

**Expected Solution**
A call to handlesubmit() function after time is over.

**Additional context**
You can use setTimeout() or setInterval() funtions

**Comment by Jaagrav** [comment]
Hey, I am interested in working on this, can you assign me please?

**Comment by ksagraya** [comment]
Hey, I would like to work on it. Can you assign it to me as a part of GSSOC 2021?

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue. Could you please assign it to me?

Thanks!!

**Comment by VrindaTyagi** [comment]
Hey, is this issue up for assignment? I would like to work on it.

**Comment by AasthaGoyalgit** [comment]
Thanks for assigning me this issue. I'm working on it.

**Comment by ksagraya** [comment]
Thanks for assigning me the issue, looking forward to work on it :)

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by naqeeb2710** [comment]
Hey , I would Like to Work On This Issue

**Comment by naqeeb2710** [comment]
hey, can you guide me on this issue?

**Comment by aavishkarmishra** [comment]
> hey, can you guide me on this issue?

You have to submit the test the after test duration is up after starting the test.

**Comment by shobit1337** [comment]
@aavishkarmishra Is this feature is still required to add? if yes, You can assign it to me.. I would like to work on it.

**Comment by VenomFate-619** [comment]
Hey 👋🏽  , I would like to work on this issue

**Comment by aavishkarmishra** [comment]
@VenomFate-619 You can create a pull request and ping me anything is required from my side.

**Comment by Yash-271120** [comment]
Is this issue resolved??
If not so I wish to work on this issue please assign it to me!!
