### ISSUE TITLE
Enhance Test card 

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#62]
Please add **Max marks and duration** of the test in the test card.

And if you can enhance the UI of test card it will be appreciated.

**Comment by aavishkarmishra** [comment]
I will assign this issue to you, ping me if anything is required from my end.

**Comment by muskaan-ag09** [comment]
@aavishkarmishra Please assign this task to me.

**Comment by Kriti-bit** [comment]
I would like to work on this, please assign this task to me
