### ISSUE TITLE
Adding Unit Tests to the frontend

### ISSUE THREAD

**Issue by mohitms007** [Manthan933/Manthan#65]
**Is your feature request related to a problem? Please describe.**
A good project should always have tests included so I want to test individual components of the website to make it more reliable and scable.

**Describe the solution you'd like**
I want to test the react components with jest and include the tests folder so that the maintainers can easily test the application.

**Describe alternatives you've considered**
There can be many alternatives to jest but jest will be more compatible.

**Comment by mohitms007** [comment]
Can I be assigned this issue?

**Comment by aavishkarmishra** [comment]
I am assigning this issue to you, please proceed with this issue and ping our mentors on GSSoC server if any help is required.

**Comment by mohitms007** [comment]
Alright I am going to start working on it. Thanks!

**Comment by mohitms007** [comment]
Update: will finish in a day or two.
