### ISSUE TITLE
Issue while logging out

### ISSUE THREAD

**Issue by Sukriti-sood** [Manthan933/Manthan#66]
**Describe the bug**
On logging out from a class,It  remain on the class.

![Manthan](https://user-images.githubusercontent.com/55010599/110603937-8e338b00-81ad-11eb-9ecc-e1c98c87db43.png)
@aavishkarmishra Please See , Is it considerable for the issue and can you assign it to me?

**Comment by Sukriti-sood** [comment]
@aavishkarmishra  How to know about Mentors

**Comment by aavishkarmishra** [comment]
> @aavishkarmishra How to know about Mentors

You can see them on project channel for manthan in GSSoC discord server.
