### ISSUE TITLE
Option to view students

### ISSUE THREAD

**Issue by Vidisha-kayal** [Manthan933/Manthan#7]
**Is your feature request related to a problem? Please describe.**
There is no section to view the students who have enrolled in the classroom to give the test.

**Describe the solution you'd like**
It would be nice if there is an option to view the students who have enrolled in the classroom.

**Comment by N00Bmaster2810** [comment]
@aavishkarmishra sir, if this issue is available can I work on it under SWOC?

**Comment by aavishkarmishra** [comment]
> @aavishkarmishra sir, if this issue is available can I work on it under SWOC?
Yes, I will assign this issue to you and please create a pull request within a week so that we can assign mentors to you.
