### ISSUE TITLE
Issue in google login

### ISSUE THREAD

**Issue by mn-gt** [Manthan933/Manthan#71]
Hey @aavishkarmishra when I am doing login by google, after selecting Gmail id it is showing error-

![2021-03-11](https://user-images.githubusercontent.com/69010912/110816663-8d841d00-82b1-11eb-8538-7d58dab91e0c.png)

 So I want to work on this issue as a GSSOC participants, Please assign it to me-

**Comment by iamabhi222** [comment]
> Hey @aavishkarmishra when I am doing login by google, after selecting Gmail id it is showing error-
> 
> ![2021-03-11](https://user-images.githubusercontent.com/69010912/110816663-8d841d00-82b1-11eb-8538-7d58dab91e0c.png)
> 
> So I want to work on this issue as a GSSOC participants, Please assign it to me-

can you please also include the URL in the SS

**Comment by iamabhi222** [comment]
I don't see any issue there so closing this till we find one.
