### ISSUE TITLE
No of students enrolled not placed properly

### ISSUE THREAD

**Issue by dig9074vijay** [Manthan933/Manthan#78]
**No of students enrolled number not placed properly**

**To Reproduce**
1. Go to 'NavBar'
2. Click on 'Three Horizontal Lines Icons' 
3. See error (Number is displayed below enrolled)

**Expected behavior**
Number of students enrolled should appear in front the 'enrolled' text.

**Screenshots**
![bandicam 2021-03-12 08-35-50-927](https://user-images.githubusercontent.com/55308273/110970581-bd154280-830e-11eb-9b11-3b16e1f9191f.jpg)

**Desktop **
 - OS: Windows 10 Pro , Version 1909
 - Browser: Chrome

**Comment by Kritika495** [comment]
can I work on this issue?

**Comment by aavishkarmishra** [comment]
#51 is same issue with a pull request waiting for review
