### ISSUE TITLE
Option to remove student

### ISSUE THREAD

**Issue by Vidisha-kayal** [Manthan933/Manthan#8]
**Is your feature request related to a problem? Please describe.**
There is no option with the help of which a teacher can remove a student from the classroom.

**Describe the solution you'd like**
An option to remove any particular student from the classroom.

**Comment by Rishi-121** [comment]
I want to handle it!

**Comment by aavishkarmishra** [comment]
Hello, @Rishi-121 are you still working on this issue ? 
Please create a pull request if you need any help, or if you are not interested then we can reassign this issues to someone else.

**Comment by Kathuria** [comment]
@aavishkarmishra : Can I try to solve this issue?

**Comment by Kathuria** [comment]
@aavishkarmishra : I will start working on it, In meantime Can you please assign me this issue.

**Comment by Kathuria** [comment]
@aavishkarmishra , @Vidisha-kayal : This is similar feature to below mentioned feature.
Option for students to leave classrooms #28 

Details:
Student | For leaving Classroom - user Id will be removed from users list of particular class. Just a simple prompt to confirm to leave class.

Teacher/Admin | Similarly, For Removing Student from class - user Id will be removed from users list of particular class. Additionally here we will be having multiple users and will get an option to pick and delete, can delete all as well.

@Vidisha-kayal : Do you have any design in mind to handle this case. There can be a dropdown (placed inside class or card?) or in classroom List of users will be given where an option to remove particular student or all students button at bottom.
Sample - https://material-ui.com/components/lists/#interactive

**Comment by abhijeet010304** [comment]
Please assign this issue to me as a part of GSSOC21

**Comment by Kathuria** [comment]
@abhijeet010304 : This is already done.

cc @aavishkarmishra

**Comment by aavishkarmishra** [comment]
> @aavishkarmishra , @Vidisha-kayal : This is similar feature to below mentioned feature.
> Option for students to leave classrooms #28
> 
> Details:
> Student | For leaving Classroom - user Id will be removed from users list of particular class. Just a simple prompt to confirm to leave class.
> 
> Teacher/Admin | Similarly, For Removing Student from class - user Id will be removed from users list of particular class. Additionally here we will be having multiple users and will get an option to pick and delete, can delete all as well.
> 
> @Vidisha-kayal : Do you have any design in mind to handle this case. There can be a dropdown (placed inside class or card?) or in classroom List of users will be given where an option to remove particular student or all students button at bottom.
> Sample - https://material-ui.com/components/lists/#interactive

It will better if you can create a tab with list of student for respective class from where admin can remove any student, similar to google classroom.

**Comment by Kathuria** [comment]
@abhijeet010304 : You can try this with above approach mentioned by @aavishkarmishra .
@aavishkarmishra : Please assign this issue to @abhijeet010304 - if he can work on this new approach for removing the student.
