### ISSUE TITLE
Test can be created anonymously

### ISSUE THREAD

**Issue by JadeMaveric** [Manthan933/Manthan#83]
**Describe the bug**
Creation of tests should only be limited to the teacher (Google Classrooms assumes this is the creator of the test). But the current system allows not only an random user logged in to create test, but also anonymous users on the internet. This is basic security requirement, and that would prevent anyone from using this app in a serious environment.

**To Reproduce**
1. I've set up a class room. Go to 'http://www.manthan-app.org/A0jp8s' (even works in incognito)
2. You should be presented with the create test menu.
3. Setup the test the way you want.
4. If you're signed up for the course, the test should be appear in the course dashboard.
5. Enjoy trolling students

**Expected behavior**
Unauthenticated users are redirected to the login page, while unauthorized users (students) are redirected to the course dashboard. An authorization mechanism that prevents people trolling the system is absolutely required. A prerequisite to this would be a user database (which I'm assuming is #80). Additional creator and enrolled students metadata would have to be added to the course.

**Screenshots**
(This is a private window in firefox)
![image](https://user-images.githubusercontent.com/12978899/111021125-3a64b400-83f0-11eb-9029-36bbadcb30dd.png)

**Comment by JadeMaveric** [comment]
For a proper OAuth system I'd recommend switching to a backend library like passportjs. It provides middlewares for express that maintain login information via sessions (even persistent ones using cookies). This is more robust system that doing things client side. As a bonus, it also allows for authentication from multiple providers.

**Comment by AshuKV** [comment]
Hey, I am interested in working on this. Can I work on this issue under GSSOC'21?

**Comment by Vidisha-kayal** [comment]
@AshuKV yes

**Comment by AshuKV** [comment]
@Vidisha-kayal Can you please add another contributors to work on the same issue with me.

**Comment by osamamagdy** [comment]
Hey @Vidisha-kayal , I am a GSSoC 2021 participant
I want to work on this along with @AshuKV  if applicable

**Comment by osamamagdy** [comment]
@AshuKV can you mail me at osamamagdy174@gmail.com to communicate about how should we approach the solution. Also, i think we should have a meeting together asap 😃

**Comment by osamamagdy** [comment]
@Vidisha-kayal  as @AshuKV is not responding I will start working on this on my own. and sending daily updates here.
*Day 1*
First: it came to me that there is no authentication system on the website at all, so I think that there is a need for a signup/login page for the website and also using authentication middlewares we have to check for authentication and authorization of each user first before allowing him to create, get any test/classroom

**Comment by osamamagdy** [comment]
@Vidisha-kayal could you gave me feedback that my approach for the fix is right 
Also, I would like to mention that this work is very big for one person so I will need another contributor with me.
I am waiting for @AshuKV to reach to me so we can start immediately.

**Comment by osamamagdy** [comment]
@Vidisha-kayal  as @AshuKV is not responding I will start working on this on my own. and sending daily updates here.
*Day 1*
First: it came to me that there is no authentication system on the website at all, so I think that there is a need to redirect for a separate signup/login page for the website and also using authentication middlewares we have to check for authentication and authorization of each user first before allowing him to create, get any test/classroom

**Comment by osamamagdy** [comment]
@Vidisha-kayal can you tell me the feedback about this approach. Also, I can't find the login/signup routes aren't they implemented?

**Comment by AshuKV** [comment]
Hey @osamamagdy I have mailed you my skype id hours back. Please do check. We can connect anytime

**Comment by osamamagdy** [comment]
@AshuKV mailed you back.

**Comment by aavishkarmishra** [comment]
> @Vidisha-kayal can you tell me the feedback about this approach. Also, I can't find the login/signup routes aren't they implemented?

There is an implementation for User sign up and login routes but they are not being used for now, you can use that.

**Comment by osamamagdy** [comment]
@aavishkarmishra 
I and @AshuKV  are working on it now and we will continue from the pull request that was merged in #120

**Comment by osamamagdy** [comment]
@JadeMaveric @AshuKV @aavishkarmishra @aavishkarmishra @Vidisha-kayal  I created a PR #128 for this issue
Can you review it 😃
