### ISSUE TITLE
No need to use body-parser when using express version 4.16+

### ISSUE THREAD

**Issue by abhay27chauhan** [Manthan933/Manthan#85]
##Proposal

Express version 4.16+, their own body-parser implementation is now included in the default Express package so there is no need for you to download another dependency.

You have added a line to your code that looks like the following:

- app.use(bodyparser.json());

If you are using Express 4.16+ you can now replace that line with:

- **app.use(express.json());**

You also have the following code in your environment:

- app.use(bodyParser.urlencoded({extended: true}));

You can replace that with:

- **app.use(express.urlencoded());**

**Comment by abhay27chauhan** [comment]
I am a participant of GSSOC21, so please let me know if this is a valid proposal

**Comment by aavishkarmishra** [comment]
@abhay27chauhan Feel free to create pull request for this issue
