### ISSUE TITLE
Errors are not handled properly while creating the test.

### ISSUE THREAD

**Issue by Soham-Official** [Manthan933/Manthan#87]
Bug:
1.While creating test,according to the code no one can create a test without giving a valid duration..but conditions are not set properly so we can create the test without giving any durations....

**To Reproduce**
1.Create a Class
2.Create a test
3.fill all the details without giving marks
4.click next

**Expected behavior**
One should not be  able to create the test without giving duration
**Screenshots**
https://user-images.githubusercontent.com/54814610/111028515-21bec300-841d-11eb-9bf3-676794cc4ec6.png

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser Google chrome

**Comment by Soham-Official** [comment]
is this a valid issue?please let me know if i can work on this or not

**Comment by Vidisha-kayal** [comment]
@Soham-Official yes you can work on this

**Comment by Soham-Official** [comment]
okay thanks,i'm working on it
