### ISSUE TITLE
Class Cards are not responsive

### ISSUE THREAD

**Issue by Soham-Official** [Manthan933/Manthan#90]
**Describe the bug**
As there is no limiting input size while creating a class,on big names class cards are not looking good as they got static(not responsive) css designs and also Delete button got hidden so one cannot able to delete their created class if their class name is big.

**To Reproduce**
1. Go to 'Create Class'
2. Enter Big names in all fields
3. Delete button is hidden along with other informations.

**Expected behavior**
Card should be responsive to the input values
There must be a limiting range of input names

**Screenshots**
![image](https://user-images.githubusercontent.com/54814610/111030579-107bb380-8429-11eb-8713-99c7fea504c5.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser chrome
 - Version  89.0.4389.82 (Official Build) (64-bit)

**Additional context**

**Comment by Vidisha-kayal** [comment]
@Kritika495 You can work on this issue if you are interested

**Comment by Kritika495** [comment]
Yes I am interested in working on it

**Comment by Soham-Official** [comment]
should i start working on this issue?

**Comment by Soham-Official** [comment]
i created this issue...what makes you not assigning me in this issue?can anyone please explain...i'm bit confused

**Comment by Vidisha-kayal** [comment]
@Soham-Official yes you can also start working on this issue.

**Comment by aavishkarmishra** [comment]
Please update the UI for navbar too
![image](https://user-images.githubusercontent.com/58372823/111496584-6ff9fc00-8766-11eb-9eaf-d7181f8cb20c.png)

**Comment by Soham-Official** [comment]
Okay..i'm working on it
