### ISSUE TITLE
Test validation

### ISSUE THREAD

**Issue by nishant23122000** [Manthan933/Manthan#91]
I notice some important bugs Please read it below in details,

I created new test and i enter negative marks also add long hours and minutes . but still there is not an error or proper validation. see below screenshot,

![Capture](https://user-images.githubusercontent.com/53515714/111032489-7e78a880-8432-11eb-8a5b-8b328ec079ff.PNG)

![Capture2](https://user-images.githubusercontent.com/53515714/111032514-a2d48500-8432-11eb-971b-48634edd7659.PNG)

We should handle this with proper validation. 

Please check it and assign me

**Comment by Vidisha-kayal** [comment]
@nishant23122000 This issue is same with #84

**Comment by nishant23122000** [comment]
ohk no problem i forget to show it @Vidisha-kayal

**Comment by nishant23122000** [comment]
Hey @Vidisha-kayal  i completed this issue just . can you check it .
if It's correct then i send pull request otherwise it will be ok to continue working of #84

https://user-images.githubusercontent.com/53515714/111035062-91917580-843e-11eb-9760-2f0beb8a954d.mp4

**Comment by Vidisha-kayal** [comment]
@nishant23122000 Its ok please send the pull request in #84
