### ISSUE TITLE
Adding various security features

### ISSUE THREAD

**Issue by udaymittal7** [Manthan933/Manthan#94]
Setting various HTTP headers using helmet
Data sanitization against no SQL injection and XSS 
Rate limiter so the server won't get overload
Preventing parameter pollution

If you find it relevant, please assign me.
I am a participant of GGSOC, so please add the relevant tags too.

**Comment by VenomFate-619** [comment]
Can I do this?

**Comment by subhangi2731** [comment]
please assign me

**Comment by subhangi2731** [comment]
@aavishkarmishra can you please help me in this issue. I have some doubts?
