### ISSUE TITLE
No need of body-parser in express version 4.16+

### ISSUE THREAD

**Issue by udaymittal7** [Manthan933/Manthan#97]
Express version 4.16+, their own body-parser implementation is now included in the default Express package so there is no need for you to download another dependency.

You have added a line to your code that looks like the following:

app.use(bodyparser.json());
If you are using Express 4.16+ you can now replace that line with:

app.use(express.json());
You also have the following code in your environment:

app.use(bodyParser.urlencoded({extended: true}));
You can replace that with:

app.use(express.urlencoded());

If you find it relevant, please assign me and add the relevant tags. Thank you.

**Comment by aavishkarmishra** [comment]
#85 is the same issue.
