### ISSUE TITLE
Generate class code link

### ISSUE THREAD

**Issue by nishant23122000** [Manthan933/Manthan#98]
I have a have of a new feature,

Till now, If We have to join a class we need to add class code and this feature is great, but I want to append something in this,
For example, if a user creates a class and the user wants to invite his friend to class, so he will send a link that contains class code in the URL query. and his friend can join the class by clicking the link.

So this becomes great for user experience

**Comment by aavishkarmishra** [comment]
Please continue with this amazing idea, I would love to experience this feature 💯

**Comment by aavishkarmishra** [comment]
@nishant23122000 Would you like work on this feature ?

**Comment by nishant23122000** [comment]
@aavishkarmishra  sure man 😎

**Comment by DARKPROGRAMMER16** [comment]
Can I join in with you @nishant23122000 
for this feature.??
