### ISSUE TITLE
Feature: Addition of dark mode

### ISSUE THREAD

**Issue by Aditya201551** [Manthan933/Manthan#99]
@Vidisha-kayal 

I would like to add dark mode to the web app

-> A button in the navbar to toggle light and dark mode anytime anywhere

I would like to work on this feature and deploy it as soon as possible it would be great if the team assign me this task

ThankYou(Gssoc 2021 participant)

**Comment by lakshita15** [comment]
Hello, I am a participant of GSSoC'21. I can contribute to this issue.
Please assign me this task
Thank you!

**Comment by Aditya201551** [comment]
Hello, @lakshita15 I raised this issue so I would like to work on this issue thankyou

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this as well...

**Comment by Aditya201551** [comment]
@Vidisha-kayal please assign this task to @lakshita15 or @ShambhaviSharma0110 because my exams have been started so I won't be able to work on this issue for a while so it's better to pass this issue to someone else......Thank You!

**Comment by kunal299** [comment]
@Vidisha-kayal I am really interested in working on this issue. Please assign this issue to me, I would complete it asap.

**Comment by chazuttu** [comment]
I am GSSOC'21 Participant. Please assign this issue to me and review my PR for this issue. Thank you

**Comment by SS-Ace** [comment]
Respected sir,
Can I also contribute to it?

**Comment by SS-Ace** [comment]
thank you sir for assigning it to me but sir can you verify if the repository code is correct? as i was not able to deploy it locally.

**Comment by aavishkarmishra** [comment]
> thank you sir for assigning it to me but sir can you verify if the repository code is correct? as i was not able to deploy it locally. i did npm install as instructed but still i was getting error. first the error was coming in MotionContainer.js in box part but after referring to it's previous pr i rectified it but then whole new bunch of errors showed up. Hoping for the positive response.

Please check now, and make sure you have .env file.
You can refer here for format [#installation](https://github.com/Manthan933/Manthan/blob/main/README.md#installation).

**Comment by SS-Ace** [comment]
ok sir thank you

**Comment by SS-Ace** [comment]
> 
> 
> > thank you sir for assigning it to me but sir can you verify if the repository code is correct? as i was not able to deploy it locally. i did npm install as instructed but still i was getting error. first the error was coming in MotionContainer.js in box part but after referring to it's previous pr i rectified it but then whole new bunch of errors showed up. Hoping for the positive response.
> 
> Please check now, and make sure you have .env file.
> You can refer here for format [#installation](https://github.com/Manthan933/Manthan/blob/main/README.md#installation).

yes sir now it is working.

**Comment by SS-Ace** [comment]
Sir I was able to make dark mode according to the device if device is in dark mode then the app would also be in dark mode but the button to convert it into light mode is not working. Actually the button is not clickable(also checked in the console). I have put the new code in App.js and styles.css is used for styling. Can you help in this issue?

**Comment by aavishkarmishra** [comment]
Instead of making changes in app.js you can make changes in
DashboardNavbar.js or DashboardSidebar.js and if required you can use redux
for state handling.

I hope this will help you.

You can also create the pull request, so that I can review the errors.

**Comment by SS-Ace** [comment]
Ok sir thank you🙏
